// test/fase3-presencia.test.js — Fase 3: identidad de trabajador + cobertura del
// aviso de presencia (con regla de equipo) + dry-run que no envía.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const path = require('path');
const root = path.join(__dirname, '..');

// ── Mock de ./db + patch de attendance/notifications ANTES de requerir avisoPresencia ──
const attendanceRows = []; // filas {workerId, date}
const cols = {
  attendance: {
    async findOne(q) { return attendanceRows.find(r => r.workerId === q.workerId && r.date === q.date) || null; }
  }
};
const db = { collection: (n) => cols[n] };
const dbPath = require.resolve(path.join(root, 'src/db.js'));
require.cache[dbPath] = { id: dbPath, filename: dbPath, loaded: true, exports: { getDB: async () => db } };

const attendance = require(path.join(root, 'src/attendance.js'));
let workersMock = [];
attendance.getWorkers = async () => workersMock;

const notifications = require(path.join(root, 'src/notifications.js'));
let sent = [];
notifications.sendWhatsAppTo = async (to, msg) => { sent.push({ to, msg }); return true; };

const acceso = require(path.join(root, 'src/acceso.js'));
const aviso = require(path.join(root, 'src/avisoPresencia.js'));

const HOY = new Date().toISOString().slice(0, 10);

test('identidad: los 5 números son rol trabajador', async () => {
  assert.equal(acceso.esTrabajador('whatsapp:+34672876051'), true);            // Jose
  assert.equal(acceso.matchTrabajador('+34 689 936 384'), 'javi el largo');    // formato con espacios
  const id = await acceso.resolverIdentidad('whatsapp:+34642548108');          // Abdellah
  assert.equal(id.rol, 'trabajador');
});

test('identidad: un número ajeno NO es trabajador', () => {
  assert.equal(acceso.esTrabajador('+34600000000'), false);
  assert.equal(acceso.matchTrabajador('+34600000000'), null);
});

test('dry-run: pendientes = con whatsapp y SIN presencia hoy (equipo cubierto excluido); no envía', async () => {
  workersMock = [
    { id: 'w1', name: 'Jose Beliard' },     // whatsapp por mapa, sin presencia → pendiente
    { id: 'w2', name: 'Abdellah Souiri' },  // tiene registro hoy (fichado por equipo) → NO
    { id: 'w3', name: 'Diego Campillo' },   // sin whatsapp (baja) → NO aparece
  ];
  attendanceRows.length = 0;
  attendanceRows.push({ workerId: 'w2', date: HOY }); // Abdellah consta (autoGenerated por equipo)
  sent = [];

  const r = await aviso.enviarAvisoPresencia({ dryRun: true });
  assert.deepEqual(r.resultado.map(x => x.name), ['Jose Beliard']);
  assert.equal(r.pendientes, 1);
  assert.equal(sent.length, 0, 'dry-run NO envía');
});

test('quien ya fichó él mismo tampoco recibe aviso', async () => {
  workersMock = [{ id: 'w1', name: 'Jose Beliard' }];
  attendanceRows.length = 0;
  attendanceRows.push({ workerId: 'w1', date: HOY });
  const r = await aviso.enviarAvisoPresencia({ dryRun: true });
  assert.equal(r.pendientes, 0);
});

test('envío real: manda a los pendientes por sendWhatsAppTo', async () => {
  workersMock = [{ id: 'w1', name: 'Jose Beliard' }];
  attendanceRows.length = 0;
  sent = [];
  const r = await aviso.enviarAvisoPresencia({ dryRun: false });
  assert.equal(r.pendientes, 1);
  assert.equal(sent.length, 1);
  assert.match(sent[0].to, /\+34672876051/);
});
