// src/attendance.js — v5 con cálculo correcto de bajas, costes y días cliente
const { MongoClient } = require('mongodb');
const CONFIG = require('./config');

let db = null;
let connecting = false;

async function getDB() {
  return require('./db').getDB();
}

const WORKERS = CONFIG.workersFallback;
const ESTADOS = CONFIG.estadosPresencia;

let _workersCache     = null;
let _workersCacheTime = 0;

function _invalidateWorkersCache() {
  _workersCache     = null;
  _workersCacheTime = 0;
  console.log('[Attendance] Caché de workers invalidada');
}

async function getWorkers() {
  if (_workersCache && Date.now() - _workersCacheTime < 5 * 60 * 1000) return _workersCache;
  try {
    const { getUsers } = require('./users');
    const users   = await getUsers(false);
    const workers = users
      .filter(u => u.role === 'tech' || u.role === 'office')
      .map(u => ({
        id:        String(u._id),
        name:      u.name,
        color:     u.color     || '#4d9cf8',
        costeHora: u.costeHora || CONFIG.getRateForWorker(u),
        nota:      u.nota      || '',
      }));
    if (workers.length > 0) {
      _workersCache     = workers;
      _workersCacheTime = Date.now();
      return workers;
    }
  } catch(e) {
    console.warn('[Attendance] Usando workers fallback:', e.message);
  }
  return CONFIG.workersFallback;
}

async function saveAttendance(entry) {
  const db = await getDB();

  // Guardamos la entrada previa para saber a quién había en el equipo antes
  // (y poder limpiar lo que ya no corresponda).
  const prev = await db.collection('attendance').findOne({ workerId: entry.workerId, date: entry.date });

  // Un guardado directo (desde el modal) marca la entrada como "propia":
  // quitamos las banderas de autogenerada. Y si la entrada NO trae lista de
  // obras (guardado de un solo cliente), limpiamos cualquier lista previa para
  // que un día pase de varias obras a una sola sin dejar restos.
  const unsetDoc = { autoGenerated: '', autoFromEquipo: '' };
  if (!Array.isArray(entry.obras)) unsetDoc.obras = '';

  const result = await db.collection('attendance').updateOne(
    { workerId: entry.workerId, date: entry.date },
    {
      $set:   { ...entry, updatedAt: new Date() },
      $unset: unsetDoc,
    },
    { upsert: true }
  );

  // Enlaza la presencia de los compañeros de plantilla del equipo
  try { await syncTeamPresence(db, entry, prev); }
  catch (e) { console.warn('[Attendance] syncTeamPresence:', e.message); }

  return result;
}

// Cuando marcas a un compañero de PLANTILLA en "quién estuvo ese día", le
// creamos/actualizamos su propia presencia ese día (mismo cliente). Reglas:
//   · nunca pisamos una entrada que él tenga puesta a mano,
//   · si lo quitas del equipo, borramos solo la que le habíamos autogenerado,
//   · no encadenamos (la entrada autogenerada lleva equipo vacío).
// Nota: el modelo permite una sola presencia por trabajador y día, así que se
// asume que un trabajador está en un único sitio por jornada.
async function syncTeamPresence(db, entry, prev) {
  const date = entry.date;
  const src  = String(entry.workerId);

  const plantillaIds = e => (Array.isArray(e && e.equipo) ? e.equipo : [])
    .filter(m => m && m.tipo === 'plantilla' && m.id && String(m.id) !== src)
    .map(m => String(m.id));

  // Si el estado no es "obra", no hay equipo que propagar: el conjunto nuevo es
  // vacío, de modo que se limpie lo que hubiéramos generado antes.
  const nuevos     = entry.estado === 'obra' ? new Set(plantillaIds(entry)) : new Set();
  const anteriores = new Set(plantillaIds(prev));

  // 1) Compañeros que ya no están -> borrar su presencia SOLO si la generamos
  //    nosotros desde este mismo trabajador y él no la ha tocado.
  for (const id of anteriores) {
    if (nuevos.has(id)) continue;
    const ex = await db.collection('attendance').findOne({ workerId: id, date });
    if (ex && ex.autoGenerated && ex.autoFromEquipo === src) {
      await db.collection('attendance').deleteOne({ workerId: id, date });
    }
  }

  // 2) Compañeros actuales -> crear/refrescar su presencia sin pisar lo manual.
  const equipoActual = entry.estado === 'obra' && Array.isArray(entry.equipo) ? entry.equipo : [];
  for (const m of equipoActual) {
    if (!m || m.tipo !== 'plantilla' || !m.id || String(m.id) === src) continue;
    const id = String(m.id);
    const ex = await db.collection('attendance').findOne({ workerId: id, date });

    // Tiene entrada propia (manual) o generada por OTRO trabajador: no la tocamos.
    if (ex && !(ex.autoGenerated && ex.autoFromEquipo === src)) continue;

    await db.collection('attendance').updateOne(
      { workerId: id, date },
      { $set: {
          workerId:     id,
          workerName:   m.nombre || '',
          date,
          estado:       'obra',
          clientName:   entry.clientName || '',
          horas:        parseFloat(entry.horas || 8),
          tipoJornada:  entry.tipoJornada || 'normal',
          notas:        `Añadido automáticamente (equipo de ${entry.workerName || 'un compañero'})`,
          equipo:       [],
          autoGenerated: true,
          autoFromEquipo: src,
          updatedAt:    new Date(),
        } },
      { upsert: true }
    );
  }
}

// Une dos listas de equipo evitando duplicados (por id o, si no, por nombre).
function mergeEquipo(a, b) {
  const out = [];
  const seen = new Set();
  [...(Array.isArray(a) ? a : []), ...(Array.isArray(b) ? b : [])].forEach(m => {
    if (!m) return;
    const key = m.id ? 'id:' + String(m.id) : 'n:' + normName(m.nombre);
    if (seen.has(key)) return;
    seen.add(key);
    out.push(m);
  });
  return out;
}

// Devuelve la lista de obras de un día. Si la entrada es antigua (un solo
// cliente sin lista), la convierte en una lista de un elemento. Así el resto
// del código trabaja siempre con la misma forma.
function getObras(entry) {
  if (entry && Array.isArray(entry.obras) && entry.obras.length) return entry.obras;
  if (entry && entry.estado === 'obra' && entry.clientName) {
    return [{ clientName: entry.clientName, horas: parseFloat(entry.horas || 0) }];
  }
  return [];
}

// Añade una obra a la lista del día. Si ese cliente ya está ese día (dos partes
// del mismo sitio), suma las horas en la misma línea en vez de duplicarla.
function addObra(list, clientName, horas) {
  const out = (Array.isArray(list) ? list : []).map(o => ({ ...o }));
  const key = normName(clientName);
  const found = out.find(o => normName(o.clientName) === key);
  if (found) found.horas = parseFloat(found.horas || 0) + parseFloat(horas || 0);
  else       out.push({ clientName: clientName || 'Sin cliente', horas: parseFloat(horas || 0) });
  return out;
}

// Cuando un trabajador sube un parte, reflejamos su presencia de ese día.
// Un trabajador puede ir a varios sitios el mismo día: cada parte AÑADE su obra
// a la lista del día (no pisa la anterior) y las horas del día se SUMAN.
// No pisa lo que el admin pusiera en otro estado (oficina, baja...): en ese
// caso solo marca que tiene parte.
async function syncPresenceFromParte(parte) {
  if (!parte || !parte.workerId || !parte.date) return;
  const db = await getDB();
  const workerId   = String(parte.workerId);
  const existing   = await db.collection('attendance').findOne({ workerId, date: parte.date });
  const equipoParte = Array.isArray(parte.equipo) ? parte.equipo : [];
  const parteHoras  = parseFloat(parte.horas || 0);
  const parteCli    = parte.clientName || 'Sin cliente';

  // Conflicto: el admin lo marcó en un estado que no es obra. No lo pisamos.
  if (existing && existing.estado && existing.estado !== 'obra') {
    const e = { ...existing };
    delete e._id;
    e.tieneParte = true;
    await saveAttendance(e);
    return;
  }

  // Día de obra (o nuevo): acumulamos la obra del parte en la lista del día.
  const obras      = addObra(getObras(existing), parteCli, parteHoras);
  const totalHoras = obras.reduce((s, o) => s + parseFloat(o.horas || 0), 0);

  const entry = {
    workerId,
    workerName:  (existing && existing.workerName) || parte.workerName || '',
    date:        parte.date,
    estado:      'obra',
    obras,                              // lista de obras del día
    clientName:  obras[0].clientName,   // principal (para vista/compatibilidad)
    horas:       totalHoras,            // total del día (suma)
    notas:       (existing && existing.notas) || '',
    tieneParte:  true,
    tipoJornada: (existing && existing.tipoJornada) || parte.tipoJornada || 'normal',
    equipo:      mergeEquipo(existing && existing.equipo, equipoParte),
  };

  await saveAttendance(entry);
}

// Cuando un trabajador FICHA su entrada, marcamos que estuvo presente ese día.
// No pisa lo que ya hubiera (parte, estado del admin): solo añade la marca
// `fichado`. Si no existía entrada, crea una mínima de presencia (obra, 0 h;
// las horas reales las pone el parte si lo hay).
async function marcarPresenciaFichaje(workerId, workerName, date) {
  if (!workerId || !date) return;
  const db = await getDB();
  await db.collection('attendance').updateOne(
    { workerId: String(workerId), date },
    { $set: { fichado: true, fichajeAt: new Date(), workerName: workerName || undefined },
      $setOnInsert: { workerId: String(workerId), date, estado: 'obra', obras: [], horas: 0, autoGenerated: true, autoFromFichaje: true } },
    { upsert: true }
  );
}

// Cuando el trabajador FICHA su salida (cierra un tramo), reflejamos las horas
// realmente trabajadas en su presencia del día. Solo si la presencia sigue
// siendo la generada por el fichaje (autoGenerated + autoFromFichaje): si hay
// parte o el admin la editó, NO la pisamos (esas horas mandan).
async function actualizarHorasFichaje(workerId, date, horas) {
  if (!workerId || !date) return;
  const db = await getDB();
  await db.collection('attendance').updateOne(
    { workerId: String(workerId), date, autoGenerated: true, autoFromFichaje: true, estado: 'obra' },
    { $set: { horas: Math.round((parseFloat(horas) || 0) * 100) / 100, updatedAt: new Date() } }
  );
}

async function deleteAttendance(workerId, date) {
  const db = await getDB();
  // Al borrar la presencia de un trabajador, limpiamos también las presencias
  // que se hubieran autogenerado a partir de su equipo ese día.
  await db.collection('attendance').deleteMany({ date, autoGenerated: true, autoFromEquipo: String(workerId) });
  return db.collection('attendance').deleteOne({ workerId, date });
}

async function getAttendance({ workerId, from, to, clientName } = {}) {
  const db = await getDB();
  const query = {};
  if (workerId)   query.workerId   = workerId;
  if (clientName) query.clientName = { $regex: clientName, $options: 'i' };
  if (from || to) {
    query.date = {};
    if (from) query.date.$gte = from;
    if (to)   query.date.$lte = to;
  }
  return db.collection('attendance').find(query).sort({ date: -1 }).toArray();
}

// Normaliza un nombre para comparar (sin mayúsculas, acentos ni espacios sobrantes)
function normName(s) {
  return (s || '').toString().trim().toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

async function getMonthlySummary(year, month) {
  const db   = await getDB();
  const from = `${year}-${String(month).padStart(2,'0')}-01`;
  const to   = `${year}-${String(month).padStart(2,'0')}-31`;
  const entries = await db.collection('attendance')
    .find({ date: { $gte: from, $lte: to } })
    .sort({ date: 1 }).toArray();

  const workersList = await getWorkers();
  // Nombres de plantilla normalizados, para no contar como "ayudante externo"
  // a alguien de plantilla que se apuntó a mano antes de darlo de alta.
  const registeredNames = new Set(workersList.map(w => normName(w.name)));
  const byWorker = {};
  workersList.forEach(w => {
    byWorker[w.id] = {
      ...w,
      dias:              0,
      horas_productivas: 0,
      horas_coste:       0,
      coste_real:        0,
      dias_obra:         0,
      dias_falta:        0,
      dias_baja:         0,
      dias_vacaciones:   0,
      clientes:          {},
      ayudantes:         {},
    };
  });

  entries.forEach(e => {
    const w = byWorker[e.workerId];
    if (!w) return;

    const costeHora = w.costeHora || CONFIG.getRateForWorker(w);
    const horas     = parseFloat(e.horas || 8);
    const estado    = e.estado;

    w.dias++;

    if (CONFIG.estadosSinCoste.includes(estado)) {
      // libre — no suma nada

    } else if (CONFIG.estadosSinHorasProductivas.includes(estado)) {
      // baja / vacaciones / falta — coste real pero 0 horas productivas
      w.horas_coste += 8;
      w.coste_real  += 8 * costeHora;
      if (estado === 'baja')                           w.dias_baja++;
      if (estado === 'vacaciones')                     w.dias_vacaciones++;
      if (estado === 'falta_i' || estado === 'falta_j') w.dias_falta++;

    } else {
      // obra / oficina — horas productivas reales
      w.horas_productivas += horas;
      w.horas_coste       += horas;
      w.coste_real        += horas * costeHora;
    }

    // Clientes — solo días en obra. Un día puede tener varias obras: repartimos
    // las horas de cada una en su cliente.
    if (estado === 'obra') {
      w.dias_obra++;
      getObras(e).forEach(o => {
        const k = o.clientName || 'Sin cliente';
        if (!w.clientes[k]) w.clientes[k] = { dias: 0, horas: 0, fechas: [] };
        w.clientes[k].dias++;
        w.clientes[k].horas += parseFloat(o.horas || 0);
        if (!w.clientes[k].fechas.includes(e.date)) {
          w.clientes[k].fechas.push(e.date);
        }
      });

      // Ayudantes externos de este día
      if (Array.isArray(e.equipo)) {
        e.equipo.forEach(m => {
          if (m.tipo === 'libre' || m.tipo === 'externo') {
            const nombre = m.nombre || '?';
            // Si el nombre coincide con un trabajador de plantilla, NO es un
            // ayudante externo: es personal de plantilla apuntado a mano. Su
            // presencia debe salir de su propia ficha, no de la lista de externos.
            if (registeredNames.has(normName(nombre))) return;
            if (!w.ayudantes[nombre]) w.ayudantes[nombre] = { dias: 0, costeHora: m.costeHora || 0 };
            w.ayudantes[nombre].dias++;
          }
        });
      }
    }
  });

  const result = Object.values(byWorker).map(w => ({
    ...w,
    horas: w.horas_productivas, // compatibilidad con código existente
  }));

  return { year, month, byWorker: result, entries };
}

function buildClientSummary(byWorker) {
  const clientMap = {};

  byWorker.forEach(w => {
    const costeHora = w.costeHora || CONFIG.getRateForWorker(w);
    Object.entries(w.clientes || {}).forEach(([client, v]) => {
      if (!clientMap[client]) {
        clientMap[client] = {
          horas:        0,
          workers:      {},
          fechas:       new Set(),
          coste:        0,
        };
      }
      clientMap[client].horas += v.horas;
      clientMap[client].workers[w.name] = (clientMap[client].workers[w.name] || 0) + v.dias;
      clientMap[client].coste += v.horas * costeHora;
      (v.fechas || []).forEach(f => clientMap[client].fechas.add(f));
    });
  });

  return Object.entries(clientMap)
    .map(([client, v]) => ({
      client,
      horas:       v.horas,
      workers:     v.workers,
      coste:       Math.round(v.coste),
      dias_unicos: v.fechas.size,
      dias_persona: Object.values(v.workers).reduce((s, d) => s + d, 0),
    }))
    .sort((a, b) => b.horas - a.horas);
}

async function getClientExtract(clientName, from, to) {
  const db = await getDB();
  const query = { estado: 'obra', clientName: { $regex: clientName, $options: 'i' } };
  if (from || to) {
    query.date = {};
    if (from) query.date.$gte = from;
    if (to)   query.date.$lte = to;
  }
  const entries = await db.collection('attendance').find(query).sort({ date: 1 }).toArray();
  const byWorker = {};
  entries.forEach(e => {
    if (!byWorker[e.workerId]) byWorker[e.workerId] = { name: e.workerName, dias: 0, horas: 0, dates: [] };
    byWorker[e.workerId].dias++;
    byWorker[e.workerId].horas += parseFloat(e.horas || 8);
    byWorker[e.workerId].dates.push(e.date);
  });
  return { clientName, from, to, byWorker, totalDias: entries.length };
}

module.exports = {
  WORKERS, ESTADOS, getWorkers,
  saveAttendance, deleteAttendance, getAttendance, syncPresenceFromParte, marcarPresenciaFichaje, actualizarHorasFichaje,
  getMonthlySummary, buildClientSummary, getClientExtract,
  _invalidateWorkersCache,
};
