// src/avisoPresencia.js — Recordatorio de presencia (Fase 3).
//
// A las 17:30 (Europe/Madrid) avisa 1-a-1, SOLO a trabajadores que:
//   · tienen número de WhatsApp (los 5 autorizados en acceso.TRABAJADORES_WA), y
//   · NO consta su presencia de hoy en la colección `attendance`.
//
// La regla de equipo se respeta GRATIS: cuando alguien ficha por su equipo,
// attendance.syncTeamPresence ya crea la entrada (autoGenerated) de cada
// compañero de plantilla ese día → esos compañeros SÍ constan → no se les avisa.
//
// Fase 3 = solo el aviso (una vía). NO parsea ni escribe presencia.

const { TRABAJADORES_WA } = require('./acceso');

async function getDB() { return require('./db').getDB(); }
const normName = s => String(s || '').trim().toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');

// Siembra el campo `whatsapp` en los users que coincidan por nombre (idempotente).
// Devuelve un informe con los que mapearon y los que NO (para revisarlo).
async function seedWhatsappTrabajadores() {
  const db = await getDB();
  const users = await require('./users').getUsers(true);
  const informe = [];
  for (const [nombre, wa] of Object.entries(TRABAJADORES_WA)) {
    const u = users.find(x => normName(x.name) === nombre);
    if (u) {
      await db.collection('users').updateOne({ _id: u._id }, { $set: { whatsapp: wa } });
      informe.push({ nombre: u.name, wa, ok: true });
    } else {
      informe.push({ nombre, wa, ok: false, motivo: 'no encontrado por nombre en users' });
    }
  }
  return informe;
}

// Resuelve el whatsapp de un worker: campo sembrado en users, o el mapa por nombre.
function whatsappDe(worker) {
  return (worker && worker.whatsapp) || TRABAJADORES_WA[normName(worker && worker.name)] || null;
}

// Trabajadores a avisar hoy: tienen whatsapp y NO consta su presencia (autoGenerated incluido).
async function pendientesDeFichar(hoy) {
  const db = await getDB();
  const workers = await require('./attendance').getWorkers(); // users tech/office activos
  const conWa = workers.map(w => ({ ...w, whatsapp: whatsappDe(w) })).filter(w => w.whatsapp);
  const pendientes = [];
  for (const w of conWa) {
    const consta = await db.collection('attendance').findOne({ workerId: String(w.id), date: hoy });
    if (!consta) pendientes.push({ id: String(w.id), name: w.name, whatsapp: w.whatsapp });
  }
  return pendientes;
}

function mensajeAviso(nombre) {
  const nombreCorto = String(nombre || '').split(' ')[0] || 'compañero';
  return `Hola ${nombreCorto} 👋 Aún no consta tu parte de hoy. Dile a la oficina de Corp dónde has trabajado (y con quién, si fuiste en equipo) para dejarlo registrado. ¡Gracias!`;
}

// Envía el aviso. Con { dryRun:true } NO envía nada: devuelve a quién SE avisaría.
async function enviarAvisoPresencia({ dryRun = false } = {}) {
  const hoy = new Date().toISOString().slice(0, 10); // coherente con el resto del código
  const pendientes = await pendientesDeFichar(hoy);
  const { sendWhatsAppTo } = require('./notifications');
  const resultado = [];
  for (const w of pendientes) {
    if (dryRun) { resultado.push({ name: w.name, to: w.whatsapp, enviado: false }); continue; }
    const enviado = await sendWhatsAppTo(w.whatsapp, mensajeAviso(w.name));
    resultado.push({ name: w.name, to: w.whatsapp, enviado });
  }
  return { hoy, dryRun, pendientes: pendientes.length, resultado };
}

module.exports = { seedWhatsappTrabajadores, pendientesDeFichar, enviarAvisoPresencia, mensajeAviso };
