// src/obraDelDia.js — En qué obra está cada trabajador hoy (y con quién), para que la Presencia se
// rellene sola desde el fichaje en vez de ponerla oficina a mano.
//
//   · sugerencias(): lo que le proponemos al fichar → la obra que oficina le haya puesto HOY en Presencia,
//     si no la de su último día, y las obras de los compañeros que ya han dicho dónde están.
//   · guardar(): el trabajador dice su obra (y con quién va) → su presencia del día y la de sus compañeros
//     que aún no la tengan. Nunca pisa lo que oficina haya puesto a mano: lo deja anotado para revisar.

async function getDB() { return require('./db').getDB(); }
const r2 = n => Math.round((Number(n) || 0) * 100) / 100;

function _obraDe(a) {
  if (!a) return null;
  const o = (a.obras || []).find(x => x && (x.obraId || x.clientName));
  if (o) return { obraId: o.obraId || null, nombre: o.clientName || '' };
  if (a.obraId || a.clientName) return { obraId: a.obraId || null, nombre: a.clientName || '' };
  return null;
}
// Hecha por oficina = no la generó el fichaje ni un compañero.
const esManual = a => !!a && !a.autoGenerated && !a.autoFromFichaje && !a.autoFromEquipo;

// ── OBRA FIJA: oficina pone a alguien en una obra varios días («Jose → obra X del 6 al 20») ──
// Colección obrasFijas {workerId, workerName, obraId, obraRef, desde, hasta|null, activa, por}.
const _fecha = s => (/^\d{4}-\d{2}-\d{2}$/.test(String(s || '')) ? String(s) : null);
async function obraFijaDe(workerId, fecha, dbArg) {
  const db = dbArg || await getDB();
  return db.collection('obrasFijas').findOne({ workerId: String(workerId), activa: true, desde: { $lte: fecha }, $or: [{ hasta: null }, { hasta: { $gte: fecha } }] }, { sort: { desde: -1 } });
}
async function listarFijas({ fecha } = {}) {
  const db = await getDB();
  const q = { activa: true }; if (fecha) Object.assign(q, { $or: [{ hasta: null }, { hasta: { $gte: fecha } }] });
  return (await db.collection('obrasFijas').find(q).sort({ workerName: 1, desde: 1 }).toArray()).map(f => ({ ...f, id: String(f._id), _id: undefined }));
}
async function crearFija({ workerId, obraId, desde, hasta } = {}, por) {
  const db = await getDB();
  const { ObjectId } = require('mongodb');
  if (!/^[a-f0-9]{24}$/.test(String(obraId || ''))) throw new Error('Elige la obra');
  const o = await db.collection('obras').findOne({ _id: new ObjectId(String(obraId)) }, { projection: { reference: 1 } });
  if (!o) throw new Error('Obra no encontrada');
  const w = (await require('./fichajeMarcas').trabajadoresQueFichan().catch(() => [])).find(x => x.id === String(workerId));
  const d = _fecha(desde) || require('./fichajeMarcas').fechaHoy(), h = _fecha(hasta);
  if (h && h < d) throw new Error('La fecha final es anterior a la de inicio');
  // Una sola obra fija a la vez por trabajador: la anterior termina el día antes.
  const prev = new Date(d + 'T12:00:00Z'); prev.setUTCDate(prev.getUTCDate() - 1);
  await db.collection('obrasFijas').updateMany({ workerId: String(workerId), activa: true, $or: [{ hasta: null }, { hasta: { $gte: d } }] }, { $set: { hasta: prev.toISOString().slice(0, 10) } });
  const doc = { workerId: String(workerId), workerName: w ? w.name : '', obraId: String(o._id), obraRef: o.reference || '', desde: d, hasta: h, activa: true, por: por || '', creada: new Date() };
  const r = await db.collection('obrasFijas').insertOne(doc);
  // Si ya ha fichado hoy sin obra (o con la de por defecto), se le pone ya.
  const hoy = require('./fichajeMarcas').fechaHoy();
  if (d <= hoy && (!h || h >= hoy)) { try { await aplicarFijaSiFalta(doc.workerId, doc.workerName, hoy); } catch (e) {} }
  return { ...doc, id: String(r.insertedId) };
}
async function quitarFija(id) {
  const db = await getDB();
  const { ObjectId } = require('mongodb');
  await db.collection('obrasFijas').updateOne({ _id: new ObjectId(String(id)) }, { $set: { activa: false, quitadaAt: new Date() } });
  return { ok: true };
}
// Al fichar la entrada sin elegir obra: si oficina le tiene una obra fija, esa (y queda marcado 📌).
async function aplicarFijaSiFalta(workerId, workerName, fecha) {
  const db = await getDB();
  const f = await obraFijaDe(workerId, fecha, db); if (!f) return null;
  const a = await db.collection('attendance').findOne({ workerId: String(workerId), date: fecha });
  if (a && (_obraDe(a) && !a.dePartes)) return null;           // ya tiene obra (suya, de oficina o de un compañero)
  if (a && a.estado && a.estado !== 'obra') return null;         // vacaciones, baja…
  await guardar(workerId, workerName, fecha, { obraId: f.obraId, fija: true });
  return f;
}
// Para el resumen de las 9:15: quién ha fichado hoy y no ha dicho dónde está.
async function sinObraHoy(fecha) {
  const db = await getDB();
  const [fichados, att, plantilla] = await Promise.all([
    db.collection('fichajeMarcas').distinct('userId', { fecha, tipo: 'entrada' }),
    db.collection('attendance').find({ date: fecha }).toArray(),
    require('./fichajeMarcas').trabajadoresQueFichan().catch(() => []),
  ]);
  const por = {}; att.forEach(a => { por[a.workerId] = a; });
  return plantilla.filter(w => fichados.map(String).includes(w.id) && !w.porPartes && !(por[w.id] && (_obraDe(por[w.id]) || (por[w.id].estado && por[w.id].estado !== 'obra'))));
}

async function sugerencias(workerId, fecha) {
  const db = await getDB();
  const id = String(workerId);
  const [hoy, previos, deHoy, fichados, plantilla] = await Promise.all([
    db.collection('attendance').findOne({ workerId: id, date: fecha }),
    db.collection('attendance').find({ workerId: id, date: { $lt: fecha }, estado: 'obra' }).sort({ date: -1 }).limit(10).toArray(),
    db.collection('attendance').find({ date: fecha, workerId: { $ne: id }, estado: 'obra' }).toArray(),
    db.collection('fichajeMarcas').find({ fecha, tipo: 'entrada' }).project({ userId: 1, userName: 1 }).toArray(),
    require('./fichajeMarcas').trabajadoresQueFichan().catch(() => []),
  ]);
  const ultimo = previos.find(a => _obraDe(a) && !a.dePartes);
  const obraHoy = hoy && hoy.dePartes ? null : _obraDe(hoy);
  const fija = await obraFijaDe(id, fecha, db);
  const yo = plantilla.find(w => w.id === id);
  // Compañeros: los que ya han fichado hoy primero, luego el resto de la plantilla.
  const fichadoHoy = new Set(fichados.map(m => String(m.userId)));
  const obraDeCompa = {}; deHoy.forEach(a => { const o = _obraDe(a); if (o) obraDeCompa[a.workerId] = o; });
  const equipoAyer = new Set(((ultimo && ultimo.equipo) || []).map(e => String(e.id)).filter(Boolean));
  const companeros = plantilla.filter(w => w.id !== id).map(w => ({ id: w.id, nombre: w.name, haFichado: fichadoHoy.has(w.id), obra: obraDeCompa[w.id] || null, ayerConmigo: equipoAyer.has(w.id) }))
    .sort((a, b) => (b.haFichado - a.haFichado) || (b.ayerConmigo - a.ayerConmigo) || a.nombre.localeCompare(b.nombre));
  return {
    fecha,
    porPartes: !!(yo && yo.porPartes),
    dePartes: !!(hoy && hoy.dePartes), equipoHoy: ((hoy && hoy.equipo) || []).map(e => e.nombre), partesPor: hoy && hoy.dePartes ? (hoy.obraPorCompanero || null) : null,
    fija: fija ? { obraId: fija.obraId, nombre: fija.obraRef, hasta: fija.hasta } : null,
    hoy: obraHoy ? { ...obraHoy, puestaPor: esManual(hoy) ? 'oficina' : (hoy.obraPorCompanero || (hoy.obraFija ? 'fija' : 'ti')), equipo: (hoy.equipo || []).map(e => e.nombre) }
      : fija ? { obraId: fija.obraId, nombre: fija.obraRef, puestaPor: 'fija', hasta: fija.hasta, equipo: [] } : null,
    ultima: ultimo ? { ..._obraDe(ultimo), fecha: ultimo.date } : null,
    companeros,
  };
}

async function guardar(workerId, workerName, fecha, { obraId, nombreLibre, companeros = [], partes = false, fija = false } = {}) {
  const db = await getDB();
  const id = String(workerId);
  let obra = null;
  if (obraId && /^[a-f0-9]{24}$/.test(String(obraId))) {
    const { ObjectId } = require('mongodb');
    const o = await db.collection('obras').findOne({ _id: new ObjectId(String(obraId)) }, { projection: { reference: 1 } });
    if (o) obra = { obraId: String(o._id), nombre: o.reference };
  }
  if (!obra && String(nombreLibre || '').trim()) obra = { obraId: null, nombre: String(nombreLibre).trim().slice(0, 80) };
  // De partes (varios sitios): se apunta así y al acabar se le pregunta por WhatsApp dónde han estado.
  if (!obra && partes) obra = { obraId: null, nombre: 'De partes', partes: true };
  if (!obra) throw new Error('Elige la obra');
  const extra = obra.partes ? { dePartes: true } : { dePartes: false, obraFija: !!fija };

  const plantilla = await require('./fichajeMarcas').trabajadoresQueFichan().catch(() => []);
  const comp = (Array.isArray(companeros) ? companeros : []).map(String).filter(c => c !== id)
    .map(c => plantilla.find(w => w.id === c)).filter(Boolean).slice(0, 12);
  const equipo = comp.map(w => ({ id: w.id, nombre: w.name, tipo: 'plantilla' }));

  const actual = await db.collection('attendance').findOne({ workerId: id, date: fecha });
  const propia = _obraDe(actual);
  if (esManual(actual) && propia && (propia.obraId || propia.nombre) !== (obra.obraId || obra.nombre)) {
    // Oficina ya le puso otra obra: no se pisa, se deja dicho para que lo vea en Presencia.
    await db.collection('attendance').updateOne({ _id: actual._id }, { $set: { obraDichaPorTrabajador: obra.nombre, equipoDichoPorTrabajador: equipo.map(e => e.nombre), updatedAt: new Date() } });
  } else {
    const horas = actual ? (Number(actual.horas) || 0) : 0;
    await db.collection('attendance').updateOne(
      { workerId: id, date: fecha },
      { $set: { estado: 'obra', obras: obra.partes ? [] : [{ obraId: obra.obraId, clientName: obra.nombre, horas: r2(horas) }], clientName: obra.nombre, equipo, ...extra, obraElegidaPorTrabajador: !fija && !obra.partes, workerName: workerName || undefined, updatedAt: new Date() },
        $setOnInsert: { workerId: id, date: fecha, horas: 0, autoGenerated: true, autoFromFichaje: true } },
      { upsert: true });
  }
  // Compañeros que aún no tienen obra hoy: la misma (sin pisar a nadie).
  const puestos = [];
  for (const w of comp) {
    const a = await db.collection('attendance').findOne({ workerId: w.id, date: fecha });
    if (a && (_obraDe(a) || (a.estado && a.estado !== 'obra'))) continue;   // ya tiene obra, o está de baja/vacaciones
    await db.collection('attendance').updateOne(
      { workerId: w.id, date: fecha },
      { $set: { estado: 'obra', obras: obra.partes ? [] : [{ obraId: obra.obraId, clientName: obra.nombre, horas: r2(a ? a.horas : 0) }], clientName: obra.nombre, obraPorCompanero: workerName || '', ...(obra.partes ? { dePartes: true, partesCon: id } : {}), updatedAt: new Date() },
        $setOnInsert: { workerId: w.id, workerName: w.name, date: fecha, horas: 0, autoGenerated: true, autoFromFichaje: true, autoFromEquipo: id } },
      { upsert: true });
    puestos.push(w.name);
  }
  return { ok: true, obra: obra.nombre, equipo: equipo.map(e => e.nombre), companerosPuestos: puestos, respetada: esManual(actual) && !!propia && (propia.obraId || propia.nombre) !== (obra.obraId || obra.nombre) ? propia.nombre : null };
}

module.exports = { sugerencias, guardar, obraFijaDe, listarFijas, crearFija, quitarFija, aplicarFijaSiFalta, sinObraHoy, _obraDe, esManual };
