// src/obraDelDia.js — En qué obra está cada trabajador hoy (y con quién), para que la Presencia se
// rellene sola desde el fichaje en vez de ponerla oficina a mano.
//
//   · sugerencias(): lo que le proponemos al fichar → la obra que oficina le haya puesto HOY en Presencia,
//     si no la de su último día, y las obras de los compañeros que ya han dicho dónde están.
//   · guardar(): el trabajador dice su obra (y con quién va) → su presencia del día y la de sus compañeros
//     que aún no la tengan. Nunca pisa lo que oficina haya puesto a mano: lo deja anotado para revisar.

async function getDB() { return require('./db').getDB(); }
const r2 = n => Math.round((Number(n) || 0) * 100) / 100;

function _obraDe(a) {
  if (!a) return null;
  const o = (a.obras || []).find(x => x && (x.obraId || x.clientName));
  if (o) return { obraId: o.obraId || null, nombre: o.clientName || '' };
  if (a.obraId || a.clientName) return { obraId: a.obraId || null, nombre: a.clientName || '' };
  return null;
}
// Hecha por oficina = no la generó el fichaje ni un compañero.
const esManual = a => !!a && !a.autoGenerated && !a.autoFromFichaje && !a.autoFromEquipo;

async function sugerencias(workerId, fecha) {
  const db = await getDB();
  const id = String(workerId);
  const [hoy, previos, deHoy, fichados, plantilla] = await Promise.all([
    db.collection('attendance').findOne({ workerId: id, date: fecha }),
    db.collection('attendance').find({ workerId: id, date: { $lt: fecha }, estado: 'obra' }).sort({ date: -1 }).limit(10).toArray(),
    db.collection('attendance').find({ date: fecha, workerId: { $ne: id }, estado: 'obra' }).toArray(),
    db.collection('fichajeMarcas').find({ fecha, tipo: 'entrada' }).project({ userId: 1, userName: 1 }).toArray(),
    require('./fichajeMarcas').trabajadoresQueFichan().catch(() => []),
  ]);
  const ultimo = previos.find(a => _obraDe(a));
  const obraHoy = _obraDe(hoy);
  // Compañeros: los que ya han fichado hoy primero, luego el resto de la plantilla.
  const fichadoHoy = new Set(fichados.map(m => String(m.userId)));
  const obraDeCompa = {}; deHoy.forEach(a => { const o = _obraDe(a); if (o) obraDeCompa[a.workerId] = o; });
  const equipoAyer = new Set(((ultimo && ultimo.equipo) || []).map(e => String(e.id)).filter(Boolean));
  const companeros = plantilla.filter(w => w.id !== id).map(w => ({ id: w.id, nombre: w.name, haFichado: fichadoHoy.has(w.id), obra: obraDeCompa[w.id] || null, ayerConmigo: equipoAyer.has(w.id) }))
    .sort((a, b) => (b.haFichado - a.haFichado) || (b.ayerConmigo - a.ayerConmigo) || a.nombre.localeCompare(b.nombre));
  return {
    fecha,
    hoy: obraHoy ? { ...obraHoy, puestaPor: esManual(hoy) ? 'oficina' : (hoy.obraPorCompanero || 'ti'), equipo: (hoy.equipo || []).map(e => e.nombre) } : null,
    ultima: ultimo ? { ..._obraDe(ultimo), fecha: ultimo.date } : null,
    companeros,
  };
}

async function guardar(workerId, workerName, fecha, { obraId, nombreLibre, companeros = [] } = {}) {
  const db = await getDB();
  const id = String(workerId);
  let obra = null;
  if (obraId && /^[a-f0-9]{24}$/.test(String(obraId))) {
    const { ObjectId } = require('mongodb');
    const o = await db.collection('obras').findOne({ _id: new ObjectId(String(obraId)) }, { projection: { reference: 1 } });
    if (o) obra = { obraId: String(o._id), nombre: o.reference };
  }
  if (!obra && String(nombreLibre || '').trim()) obra = { obraId: null, nombre: String(nombreLibre).trim().slice(0, 80) };
  if (!obra) throw new Error('Elige la obra');

  const plantilla = await require('./fichajeMarcas').trabajadoresQueFichan().catch(() => []);
  const comp = (Array.isArray(companeros) ? companeros : []).map(String).filter(c => c !== id)
    .map(c => plantilla.find(w => w.id === c)).filter(Boolean).slice(0, 12);
  const equipo = comp.map(w => ({ id: w.id, nombre: w.name, tipo: 'plantilla' }));

  const actual = await db.collection('attendance').findOne({ workerId: id, date: fecha });
  const propia = _obraDe(actual);
  if (esManual(actual) && propia && (propia.obraId || propia.nombre) !== (obra.obraId || obra.nombre)) {
    // Oficina ya le puso otra obra: no se pisa, se deja dicho para que lo vea en Presencia.
    await db.collection('attendance').updateOne({ _id: actual._id }, { $set: { obraDichaPorTrabajador: obra.nombre, equipoDichoPorTrabajador: equipo.map(e => e.nombre), updatedAt: new Date() } });
  } else {
    const horas = actual ? (Number(actual.horas) || 0) : 0;
    await db.collection('attendance').updateOne(
      { workerId: id, date: fecha },
      { $set: { estado: 'obra', obras: [{ obraId: obra.obraId, clientName: obra.nombre, horas: r2(horas) }], clientName: obra.nombre, equipo, obraElegidaPorTrabajador: true, workerName: workerName || undefined, updatedAt: new Date() },
        $setOnInsert: { workerId: id, date: fecha, horas: 0, autoGenerated: true, autoFromFichaje: true } },
      { upsert: true });
  }
  // Compañeros que aún no tienen obra hoy: la misma (sin pisar a nadie).
  const puestos = [];
  for (const w of comp) {
    const a = await db.collection('attendance').findOne({ workerId: w.id, date: fecha });
    if (a && (_obraDe(a) || (a.estado && a.estado !== 'obra'))) continue;   // ya tiene obra, o está de baja/vacaciones
    await db.collection('attendance').updateOne(
      { workerId: w.id, date: fecha },
      { $set: { estado: 'obra', obras: [{ obraId: obra.obraId, clientName: obra.nombre, horas: r2(a ? a.horas : 0) }], clientName: obra.nombre, obraPorCompanero: workerName || '', updatedAt: new Date() },
        $setOnInsert: { workerId: w.id, workerName: w.name, date: fecha, horas: 0, autoGenerated: true, autoFromFichaje: true, autoFromEquipo: id } },
      { upsert: true });
    puestos.push(w.name);
  }
  return { ok: true, obra: obra.nombre, equipo: equipo.map(e => e.nombre), companerosPuestos: puestos, respetada: esManual(actual) && !!propia && (propia.obraId || propia.nombre) !== (obra.obraId || obra.nombre) ? propia.nombre : null };
}

module.exports = { sugerencias, guardar };
